easy_admin:
    site_name: 'zzzzzzz'
    user:
        display_name: true
        display_avatar: false

    formats:
        number: '%d'
        datetime: 'Y-m-d H:i:s'

    entities:
        # List the entity class name you want to manage
        Post:
            class: App\Entity\Post
            label: 'tuqu'
            disabled_actions: ['new', 'edit', 'delete']
            list:
                title: 'title'
                fields: [{property: 'postid', template: 'admin/post/postid.html.twig'}, 'subject', 'idate']
            search:
                fields: ['postid', 'subject']
